# Generated by Django 5.1.7 on 2026-03-07 09:04

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifyemailtoken',
            name='token',
            field=models.CharField(default=accounts.models.generate_random_id, editable=False, max_length=4, unique=True),
        ),
    ]
