# Generated by Django 5.1.7 on 2025-04-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
