# Generated by Django 5.1.7 on 2025-04-13 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_notification_videotutorial_videocomment_savedvideo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dislikedvideo',
            old_name='tutorial',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='likedvideo',
            old_name='tutorial',
            new_name='video',
        ),
    ]
