# Generated by Django 5.1.7 on 2025-05-20 15:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_faq'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={},
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='description',
        ),
        migrations.AddField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='wallet',
            name='currency',
            field=models.CharField(default='NGN', max_length=50),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='paystack_payment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('transfer', 'Transfer'), ('withdraw', 'Withdraw')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.wallet'),
        ),
    ]
